sankey-beta
    Requirements,Design,100
    Design,Frontend Dev,40
    Design,Backend Dev,35
    Design,Database,25
    Frontend Dev,Testing,38
    Backend Dev,Testing,33
    Database,Testing,23
    Testing,Bug Fixes,15
    Testing,Deployment,79
    Bug Fixes,Testing,14
    Deployment,Production,78
