sankey-beta
    
    Energy Sources,Nuclear,25
    Energy Sources,Coal,35
    Energy Sources,Natural Gas,40
    Energy Sources,Renewable,30
    Energy Sources,Oil,20
    
    Nuclear,Electricity Generation,25
    Coal,Electricity Generation,30
    Coal,Industrial Heat,5
    Natural Gas,Electricity Generation,25
    Natural Gas,Residential Heating,10
    Natural Gas,Industrial Process,5
    Renewable,Electricity Generation,28
    Renewable,Direct Use,2
    Oil,Transportation,15
    Oil,Industrial Process,3
    Oil,Heating,2
    
    Electricity Generation,Residential,35
    Electricity Generation,Commercial,25
    Electricity Generation,Industrial,40
    Electricity Generation,Transportation,8
    
    Industrial Heat,Manufacturing,5
    Residential Heating,Homes,10
    Industrial Process,Manufacturing,8
    Direct Use,Agriculture,2
    Transportation,Cars,8
    Transportation,Trucks,4
    Transportation,Ships,2
    Transportation,Planes,1
    Heating,Buildings,2
    
    Residential,Lighting,15
    Residential,Appliances,12
    Residential,HVAC,8
    Commercial,Office Equipment,10
    Commercial,Lighting,8
    Commercial,HVAC,7
    Industrial,Motors,20
    Industrial,Process Heat,15
    Industrial,Other,5
    Transportation,Electric Vehicles,8
