packet-beta
title TCP Packet Structure
0-15: Source Port
16-31: Destination Port
32-63: Sequence Number
64-95: Acknowledgment Number
96-99: Data Offset
100-102: Reserved
103: NS
104: CWR
105: ECE
106: URG
107: ACK
108: PSH
109: RST
110: SYN
111: FIN
112-127: Window Size
128-143: Checksum
144-159: Urgent Pointer
160-191: Options (variable length)
