timeline
    title Evolution of Computing Technologies
    
    section Early Computing Era
        1940s : ENIAC Computer
             : First Electronic Computer
             : Room-sized Machine
             : Vacuum Tubes Technology
        
        1950s : UNIVAC I
             : Commercial Computer
             : Magnetic Tape Storage
             : Assembly Language
        
        1960s : IBM System/360
             : Integrated Circuits
             : Operating Systems
             : COBOL Programming
    
    section Microcomputer Revolution
        1970s : Intel 4004 Processor
             : First Microprocessor
             : Altair 8800 Kit
             : Personal Computing Begins
        
        1980s : IBM PC Standard
             : MS-DOS Operating System
             : Apple Macintosh GUI
             : Ethernet Networking
        
        1990s : World Wide Web
             : Internet Commercialization
             : Windows 95 Release
             : Mobile Phones Evolution
    
    section Internet Age
        2000s : Broadband Internet
             : Google Search Engine
             : Social Media Platforms
             : WiFi Technology
        
        2010s : Cloud Computing
             : Smartphone Revolution
             : Big Data Analytics
             : Internet of Things
        
        2020s : Artificial Intelligence
             : 5G Networks
             : Edge Computing
             : Quantum Computing
    
    section Emerging Technologies
        2025+ : Quantum Supremacy
             : Brain-Computer Interface
             : Autonomous Systems
             : Sustainable Computing
